  define (require) ->

  ###*
  # Форматирование числа.
  # @author Andrey Mishchenko (http://www.msav.ru/)
  # @param val - Значение для форматирования
  # @param thSep - Разделитель разрядов
  # @param dcSep - Десятичный разделитель
  # @returns string
  ###

  numeric_format = (val, thSep, dcSep) ->
    # Проверка указания разделителя разрядов
    thSep = ' ' if !thSep    
    # Проверка указания десятичного разделителя
    dcSep = ',' if !dcSep 
    res   = val.toString()    
    lZero = val < 0
    # Признак отрицательного числа   
    # Определение длины форматируемой части
    fLen = res.lastIndexOf('.')
    
    # До десятичной точки
    fLen = if fLen > -1 then fLen else res.length
    
    # Выделение временного буфера
    tmpRes = res.substring(fLen)
    cnt = -1
    ind = fLen
    
    while ind > 0
      # Формируем временный буфер
      cnt++
      
      if cnt % 3 == 0 and ind != fLen and (!lZero or ind > 1)
        tmpRes = thSep + tmpRes
      
      tmpRes = res.charAt(ind - 1) + tmpRes
      ind--

    tmpRes.replace '.', dcSep

  # ---
  # generated by js2coffee 2.1.0